server:
  port: 8080
  servlet:
    context-path: /community

# 数据源的配置
spring:
  redis:
    database: 0
    host: 60.204.128.243
    port: 6379
    password: Lsp1314520
  data.elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: 60.204.128.243:9300
  kafka:
    bootstrap-servers: 60.204.128.243:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.204.128.243:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: LingXi666
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: relifeme@qq.com
    # todo ：记得完成项目的时候关闭smtp
    password: ptkepfarlhkhdahe
    protocol: smtps
    properties:
      mail-smtp-ssl-enable: true
  # 关闭thymeleaf缓存 todo:打包上线记得开启
  thymeleaf:
    cache: false
# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.linshio.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# 设置日志级别
logging:
  level:
    cn.linshio.community: debug


# 自定义配置内容
community:
  path:
    # 主机域名
    domain: http://localhost:8080
    # 文件上传的路径
    upload: /Users/linshio/Project/EustiaJava/community/src/main/resources/userHeaderImg